language: go

go:
 - 1.3.1
 - tip

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -t -v ./...
 - go  install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
  on_failure: always
  on_start: never
  on_cancel: never
  on_error: never
